version: "3.9"

networks:
  starsweb_db_net:
    ipam:
      driver: default
      config:
        - subnet: "10.0.4.0/24"

services:
  db:
    image: postgres:latest
    container_name: starsweb_db
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: VI1kZmUeANrnQrCvejv4
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: starlight
    volumes:
      - /etc/starweb/pg_data:/var/lib/postgresql/data/pgdata
    networks:
      starsweb_db_net:
        ipv4_address: "10.0.4.2"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 10

  starsweb:
    image: node
    container_name: starsweb
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/starweb
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /starweb
    network_mode: host
    command: node index.js
    restart: unless-stopped
